# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/sub_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 708)
        self.Sub_window = QtWidgets.QWidget(MainWindow)
        self.Sub_window.setObjectName("Sub_window")
        self.gridLayout = QtWidgets.QGridLayout(self.Sub_window)
        self.gridLayout.setObjectName("gridLayout")
        self.main_body = QtWidgets.QVBoxLayout()
        self.main_body.setObjectName("main_body")
        self.hl_top = QtWidgets.QHBoxLayout()
        self.hl_top.setObjectName("hl_top")
        self.label_0 = QtWidgets.QLabel(self.Sub_window)
        self.label_0.setObjectName("label_0")
        self.hl_top.addWidget(self.label_0)
        self.line = QtWidgets.QFrame(self.Sub_window)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hl_top.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_top.addItem(spacerItem)
        self.comboBox_1 = QtWidgets.QComboBox(self.Sub_window)
        self.comboBox_1.setObjectName("comboBox_1")
        self.hl_top.addWidget(self.comboBox_1)
        self.comboBox_2 = QtWidgets.QComboBox(self.Sub_window)
        self.comboBox_2.setObjectName("comboBox_2")
        self.hl_top.addWidget(self.comboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_top.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.Sub_window)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hl_top.addWidget(self.line_2)
        self.checkBox_1 = QtWidgets.QCheckBox(self.Sub_window)
        self.checkBox_1.setObjectName("checkBox_1")
        self.hl_top.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.Sub_window)
        self.checkBox_2.setObjectName("checkBox_2")
        self.hl_top.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.Sub_window)
        self.checkBox_3.setObjectName("checkBox_3")
        self.hl_top.addWidget(self.checkBox_3)
        self.hl_top.setStretch(0, 6)
        self.hl_top.setStretch(3, 1)
        self.hl_top.setStretch(4, 1)
        self.hl_top.setStretch(7, 1)
        self.hl_top.setStretch(8, 1)
        self.hl_top.setStretch(9, 1)
        self.main_body.addLayout(self.hl_top)
        self.tableWidget_medium = QtWidgets.QTableWidget(self.Sub_window)
        self.tableWidget_medium.setObjectName("tableWidget_medium")
        self.tableWidget_medium.setColumnCount(0)
        self.tableWidget_medium.setRowCount(0)
        self.main_body.addWidget(self.tableWidget_medium)
        self.label_bottom = QtWidgets.QLabel(self.Sub_window)
        self.label_bottom.setObjectName("label_bottom")
        self.main_body.addWidget(self.label_bottom)
        self.gridLayout.addLayout(self.main_body, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.Sub_window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_0.setText(_translate("MainWindow", "提示框"))
        self.checkBox_1.setText(_translate("MainWindow", "RadioButton"))
        self.checkBox_2.setText(_translate("MainWindow", "RadioButton"))
        self.checkBox_3.setText(_translate("MainWindow", "RadioButton"))
        self.label_bottom.setText(_translate("MainWindow", "底部信息提示栏"))
